# Railway configuration for Receipt Store Backend
# This file automates the deployment process

[build]
builder = "nixpacks"

[deploy]
startCommand = "./main"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables (set these in Railway dashboard)
[env]
PORT = "8080"
GIN_MODE = "release"
LOG_LEVEL = "info"
LOG_FORMAT = "json"
DEV_MODE = "false"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"
DB_MAX_OPEN_CONNS = "25"
DB_MAX_IDLE_CONNS = "5"
DB_CONN_MAX_LIFETIME = "5m"
DB_CONN_MAX_IDLE_TIME = "1m"

# Manual environment variables to set in Railway:
# - DATABASE_URL (Railway will provide this when you add PostgreSQL)
# - CLERK_SECRET_KEY (your Clerk secret key from .env file)
# - REDIS_URL (Railway will provide this when you add Redis, optional)
